name: dev-pipeline

on:
  push:
    branches:
      - 'dev'
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v4
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push authorization-service
            uses: docker/build-push-action@v5
            with:
              context: ./AuthService/AuthService
              push: true
              platforms: linux/amd64,linux/arm64
              tags: zanzibarinh/authorization-service:latest
          -
            name: Build and push keycloak
            uses: docker/build-push-action@v5
            with:
              push: true
              platforms: linux/amd64,linux/arm64
              tags: zanzibarinh/keycloak:latest

